builds:
  - env:
    - CGO_ENABLED=0
  - main: main.go
    binary: sensu-opentsdb-handler
    goos:
      - linux
    goarch:
      - amd64
    ignore:

archive:
  format: tar.gz
  files:
    - LICENSE
    - README.md
    - CHANGELOG.md

  # You can change the name of the GitHub release.
  # This is parsed with the Go template engine and the following variables
  # are available:
  # - ProjectName
  # - Tag
  # - Version (Git tag without `v` prefix)
  # Default is ``
  #name_template: "{{.ProjectName}}-v{{.Version}}"
